sudo: required

language: minimal

before_install:
  - sudo apt-get install coreutils cppcheck pcregrep python3 python3-pip uncrustify

notifications:
  email:
    recipients:
    - maintainer@riot-os.org
    on_success: change
    on_failure: always

script:
  - ./RIOT/dist/tools/whitespacecheck/check.sh
  - find . -path ./RIOT -prune -o \( -name *.c -o -name *.h \) -exec cppcheck --std=c99 --enable=style --force --error-exitcode=2 --quiet -j 1 {} +
